### PR TITLE
Trying to handle camera initialization errors

### PR DESCRIPTION
**Pull request by IanButterworth**
I'm having a lot of errors trying to start and stop/start my Grasshopper 3 as mentioned in https://github.com/samuelpowell/Spinnaker.jl/issues/36. I'm sure I'm stressing the issue by testing on an Ubuntu VM, but it would be good to be able to handle initialization errors, so I'm setting that as the bar for success.

@samuelpowell Once we've fixed the `framerate!()` issue for your camera, it would be great if you could try this branch, and see if `@info "Camera Issue: Reinitializing camera"` ever occurs. 

It may be faulty hardware at my end..

About 50% of the times I try to load the gui, or start/stop the camera, either `start!(cam)` errors or the `getimage(cam,timeout=2000)` check times-out, and then the reinitialization hits maxattempts. Sometimes the reinit process does work though. Physically rebooting the camera does seem to help, but it's not 100% effective

```
julia> start()
[ Info: Checking for cameras
[ Info: Selecting camera 0
[ Info: Reading settings from camera
[ Info: Camera ready
[ Info: Starting GUI (async)
[ Info: Starting Camera Settings Updater (async)
[ Info: Starting recording listener (async)
[ Info: Starting Camera Acquisition (async)
[ Info: Camera Issue: Reinitializing camera
┌ Warning: @async error from @async runCamera()
└ @ SpinnakerGUI /media/psf/Home/Documents/Leuko/GitHub/SpinnakerGUI.jl/src/utils.jl:22
Camera couldn't be reinitialized (tried 5 times)
```

### CODE REVIEW

**Comment by IanButterworth** [comment]
Oh, and master does have some earlier attempts at catching this in it. I didn't branch out at first

**Comment by IanButterworth** [comment]
and.. It would also be good to compile a list of things to try to fix this on the camera settings. Any low hanging fruit?

**Comment by samuelpowell** [comment]
I don't have this problem.

It is a bit hit and miss as to if Spinnaker succesfully enumerates my camera though! I put that down to the library. Sometimes a bit of unplug replug required.

All I can suggest is that I put a small delay in the code after it stops the camera. Perhaps there is some asynchronous USB action going on which needs to complete before one can restart the camera....

On the occasions that `getimage` _would_ have hung, does `isrunning` return `true`? E.g. is the problem simply that starting the camera didn't work, or is it more pernicious?

**Comment by samuelpowell** [comment]
Okay I've stress tested my camera to try and recreate this, but I cannot. If enumeration is okay then I can start and stop the camera, including intermediate getimage, without any problems.

**Pull request merged**
